export const OPTIONS = {
  SKILL: [
    {value: '0', label: 'c'},
    {value: '1', label: 'c++'},
    {value: '2', label: 'C#'},
    {value: '3', label: 'Python'},
    {value: '4', label: 'Java'},
    {value: '5', label: 'JavaScript'},
    {value: '6', label: 'TypeScript'},
    {value: '7', label: 'Kotlin'},
    {value: '8', label: 'Swift'},
    {value: '9', label: 'Dart'},
    {value: '10', label: 'html'},
    {value: '11', label: 'css'},
    {value: '12', label: 'etc'},
  ],
  AGE_RANGE: [
    {value: '0', label: '10대'},
    {value: '1', label: '20대'},
    {value: '2', label: '30대 후반'},
    {value: '3', label: '40대 이상'},
  ],
  DATE_RANGE: [
    {value: '0', label: '00:00 ~ 01:00'},
    {value: '1', label: '01:00 ~ 02:00'},
    {value: '2', label: '02:00 ~ 03:00'},
    {value: '3', label: '03:00 ~ 04:00'},
    {value: '4', label: '04:00 ~ 05:00'},
    {value: '5', label: '05:00 ~ 06:00'},
    {value: '6', label: '06:00 ~ 07:00'},
    {value: '7', label: '07:00 ~ 08:00'},
  ],
  ANNUAL: [
    {value: '0', label: '0 ~ 1년차 미만'},
    {value: '1', label: '1 ~ 3년차 미만'},
    {value: '2', label: '3 ~ 5년차 미만'},
    {value: '3', label: '5 ~ 7년차 미만'},
    {value: '4', label: '8년차 이상'},
  ],
};
